name: DevOps Lab CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build, test, and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify org.jacoco:jacoco-maven-plugin:report
          mvn -B sonar:sonar \
            -Dsonar.projectKey=nareshvatte_devops-lab \
            -Dsonar.organization=nareshvatte \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Run Mutation Tests (PIT)
        continue-on-error: true
        run: |
          mvn -B org.pitest:pitest-maven:mutationCoverage \
            -DtestPlugin=junit5 \
            -Dfeatures=+EXPORT \
            -DoutputFormats=XML,HTML


